use crate::messaging::{ChatMessage, TextChannel};
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Account {
    pub id: u64,
    pub avatar: Option<String>,
    pub name: String,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Guild {
    pub id: u64,
    pub icon: Option<String>,
    pub name: String,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Channel {
    pub id: u64,
    pub guild_id: u64,
    pub name: String,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Participant {
    pub id: u64,
    pub name: String,
    pub speaking: bool,
    pub muted: bool,
    pub deafened: bool,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DeviceChoice {
    pub id: String,
    pub name: String,
    pub is_default: bool,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Phase {
    #[default]
    Offline,
    Connecting,
    SignalingReady,
    Joining,
    VoiceReady,
    VoiceWaiting,
    Reconnecting,
    Failed,
}
#[derive(Clone, Debug)]
pub struct UiState {
    pub preferences: crate::preferences::Preferences,
    pub preferences_status: String,
    pub mic_test: crate::mic_test::TestStatus,
    pub incoming_sequence: u64,
    pub dismissed_incoming: Option<(u64, Option<u64>)>,
    pub incoming_call: Option<crate::calls::IncomingCall>,
    pub notification_status: String,
    pub chat_activity: crate::chat_activity::ActivityState,
    pub history_has_more: bool,
    pub history_loading: bool,
    pub message_action_busy: bool,
    pub message_action_status: String,
    pub update_state: crate::updates::UpdateState,
    pub sound_authority: Arc<std::sync::atomic::AtomicU64>,
    pub account: Option<Account>,
    pub profiles: std::collections::HashMap<u64, crate::profiles::Profile>,
    pub guilds: Vec<Guild>,
    pub channels: Vec<Channel>,
    pub participants: Vec<Participant>,
    pub friends: Vec<crate::social::Friend>,
    pub direct_channels: Vec<crate::social::DirectChannel>,
    pub selected_dm: Option<u64>,
    pub selected_call_dm: Option<u64>,
    pub selected_call_guild: Option<u64>,
    pub social_busy: bool,
    pub social_status: String,
    pub phase: Phase,
    pub voice_handshake: Arc<songbird::DaveHandshake>,
    pub status: String,
    pub login_storage_status: String,
    pub selected_guild: Option<u64>,
    pub selected_channel: Option<u64>,
    pub muted: bool,
    pub deafened: bool,
    pub confirmed_muted: Option<bool>,
    pub confirmed_deafened: Option<bool>,
    pub server_suppressed: bool,
    pub server_deafened: bool,
    pub microphone_permission: crate::microphone::Permission,
    pub current_call: Option<crate::calls::Call>,
    pub sound_sequence: u64,
    pub sound_cue: crate::calls::Cue,
    pub call_sounds: bool,
    pub sound_volume: f32,
    pub ptt_enabled: bool,
    pub input_level: f32,
    pub output_volume: f32,
    pub revision: u64,
    pub input_devices: Vec<DeviceChoice>,
    pub output_devices: Vec<DeviceChoice>,
    pub selected_input: Option<String>,
    pub selected_output: Option<String>,
    pub audio_diagnostics: String,
    pub text_channels: Vec<TextChannel>,
    pub selected_text_channel: Option<u64>,
    pub messages: Vec<ChatMessage>,
    pub chat_busy: bool,
    pub chat_sending: bool,
    pub chat_status: String,
    pub sent_revision: u64,
}
impl Default for UiState {
    fn default() -> Self {
        Self {
            preferences: Default::default(),
            preferences_status: String::new(),
            mic_test: Default::default(),
            incoming_sequence: 0,
            dismissed_incoming: None,
            incoming_call: None,
            notification_status: "Desktop notifications are off".into(),
            chat_activity: Default::default(),
            history_has_more: false,
            history_loading: false,
            message_action_busy: false,
            message_action_status: String::new(),
            update_state: Default::default(),
            sound_authority: Arc::new(std::sync::atomic::AtomicU64::new(0)),
            account: None,
            profiles: Default::default(),
            guilds: vec![],
            channels: vec![],
            participants: vec![],
            friends: vec![],
            direct_channels: vec![],
            selected_dm: None,
            selected_call_dm: None,
            selected_call_guild: None,
            social_busy: false,
            social_status: String::new(),
            phase: Phase::Offline,
            voice_handshake: Arc::new(songbird::DaveHandshake::default()),
            status: String::new(),
            login_storage_status: String::new(),
            selected_guild: None,
            selected_channel: None,
            muted: true,
            deafened: false,
            confirmed_muted: None,
            confirmed_deafened: None,
            server_suppressed: false,
            server_deafened: false,
            microphone_permission: crate::microphone::status(),
            current_call: None,
            sound_sequence: 0,
            sound_cue: Default::default(),
            call_sounds: true,
            sound_volume: 0.3,
            ptt_enabled: false,
            input_level: 0.0,
            output_volume: 1.0,
            revision: 0,
            input_devices: vec![],
            output_devices: vec![],
            selected_input: None,
            selected_output: None,
            audio_diagnostics: "No active audio devices".into(),
            text_channels: vec![],
            selected_text_channel: None,
            messages: vec![],
            chat_busy: false,
            chat_sending: false,
            chat_status: "Choose a text channel to read its latest 50 messages.".into(),
            sent_revision: 0,
        }
    }
}
// Deliberately no Debug: Connect contains an ephemeral secret.
pub enum Command {
    StartMicTest,
    StopMicTest,
    PlayMicTest,
    SetProcessing(crate::audio_processing::ProcessingOptions),
    SetParticipantVolume {
        user_id: u64,
        volume: f32,
    },
    AnswerIncoming {
        channel: u64,
        generation: u64,
    },
    DeclineIncoming {
        channel: u64,
        generation: u64,
    },
    RequestNotificationPermission,
    SetDesktopNotifications(bool),
    LoadOlderMessages,
    ReplyMessage {
        channel_id: u64,
        message_id: u64,
        content: String,
    },
    EditMessage {
        channel_id: u64,
        message_id: u64,
        content: String,
    },
    ReactMessage {
        channel_id: u64,
        message_id: u64,
        emoji: String,
    },
    MarkChannelRead {
        channel_id: u64,
        message_id: u64,
    },
    CheckForUpdates,
    SetUpdateChecks(bool),
    SetAppearance(crate::preferences::Appearance),
    SetShortcuts(crate::shortcuts::ShortcutConfig),
    Connect {
        token: String,
        risk_accepted: bool,
        remember: bool,
    },
    #[cfg(target_os = "macos")]
    ConnectSaved {
        risk_accepted: bool,
    },
    Logout,
    Reconnect,
    RefreshSocial,
    OpenDm(u64),
    SelectDm(u64),
    CallDm(u64),
    SelectGuild(u64),
    SelectTextChannel(u64),
    RefreshMessages,
    SendMessage {
        channel_id: u64,
        content: String,
    },
    Join {
        guild_id: u64,
        channel_id: u64,
    },
    Leave,
    SetMuted(bool),
    SetDeafened(bool),
    SetPtt(bool),
    SetCallSounds(bool),
    SetSoundVolume(f32),
    SetOutputVolume(f32),
    RefreshDevices,
    SetDevices {
        input: Option<String>,
        output: Option<String>,
    },
    SetUiRepaint(Arc<dyn Fn() + Send + Sync>),
    SetUiVisible(bool),
    Quit,
}
